version: '2'
services:
    flair-pgsql:
        container_name: "development-postgres-backend"
        image: flairbi/postgres:dev
        environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=admin
        - POSTGRES_DB=fbiengine
        ports:
        - 5432:5432

    flair-couchdb:
        image: flairbi/couchdb:latest
        container_name: development-couchdb
        restart: always
        labels:
            purpose: View store
            environment: development
        environment:
            - COUCHDB_USER=admin
            - COUCHDB_PASSWORD=password
        ports:
        - 5984:5984

    flair-registry:
        container_name: "development-flair-registry"
        labels:
            purpose: Flair config server and service discovery
            environment: development
            traefik.frontend.rule: "PathPrefixStrip: /config"
            traefik.enable: true
            traefik.backend: flair-registry
            traefik.port: 8761
        image: flairbi/flair-registry:latest
        ports:
        - 8761:8761
        - 8762:8762
        environment:
        - JHIPSTER_SLEEP=0
        - SPRING_PROFILES_ACTIVE=prod
        - BITBUCKET_URI=https://github.com/viz-centric/flair-config.git

    flair-engine-grpc:
        image: flairbi/flair-engine:latest
        labels:
            purpose: Bankend engine for data calls
            environment: development
        environment:
            - CONFIG_URI=http://flair-registry:8761
            - EUREKA_URL=http://admin:admin@flair-registry:8761/eureka
            - JHIPSTER_SLEEP=60
            - SPRING_PROFILES_ACTIVE=oss,grpc
            - POSTGRES_URI=flair-pgsql:5432
            - GRPC_CERT=server.crt
            - GRPC_KEY=server.key
        ports:
        - 6565:6565

    flair-notifications:
        image: flairbi/flair-notifications:latest
        labels:
            purpose: Flair notifications
            environment: development
        ports:
        - 8090:8080
        volumes:
        - path/flair-config/flair-notifications:/flair-config
        environment:
        - APP_CONFIG=/flair-config/application-oss.yml
        - NODE_ENV=oss-dev
        - SLEEP_TIME=10

    flair-bi:
        image: flairbi/flairbi:latest
        labels:
            purpose: Flair front end application
            environment: development
            traefik.frontend.rule: "PathPrefixStrip: /flairbi"
            traefik.enable: true
            traefik.backend: flair-bi
            traefik.port: 8002
        environment:
            - CONFIG_URI=http://flair-registry:8761
            - EUREKA_URL=http://admin:admin@flair-registry:8761/eureka
            - JHIPSTER_SLEEP=60
            - SPRING_PROFILES_ACTIVE=oss
            - POSTGRES_URI=flair-pgsql:5432
        ports:
        - 8002:8002
